# =================
# 全局配置
# =================

model:
  0:
    model_name: "elevator_motor"
    model_path: "weight/elevator_motor.pt"    # 摩托车入电梯
    class_path: "model_library.model.base_model.BaseModel"
    classes: [0]
    imgsz: 1  # 1 代表模型采用原图大小

  1:
    model_name: "fire_lane_blockage"
    class_path: "model_library.model.track_fireland.TrackFireland"
    classes: [0]
    model_path: "weight/fire_lane_blockage.pt"  # 消防通道占用
    time_threshold: 60  # 消防通道占用时间阈值
    imgsz: 1  # 1 代表模型采用原图大小

  2:
    model_name: "fire_detect"
    class_path: "model_library.model.base_model.BaseModel"
    model_path: "weight/fire_detect.pt"    # 火点检测
    classes: [0]
    imgsz: 1  # 1 代表模型采用原图大小


  3:
    model_name: "accident"
    class_path: "model_library.model.track_accident.TrackAccident"
    model_path: "weight/yolo_accident_obb.pt"    # 事故检测
    # model_path: "weight/yolo_accident_obb_v2.pt"    # 事故检测_20251023
    # model_path: "weight/yolo_accident_obb_havegame_nomoni.pt"    # 事故检测_20251024
    classes: [0]
    config: 0.75
    time_step: 60  # 消息推送的间隔
    imgsz: 1  # 1 代表模型采用原图大小


  4:
    model_name: "license plate"
    class_path: "model_library.model.plate_model.PlateModel"
    model_path: "weight/best_epoch32_CCPDfintune_baseYOLOv11.pt"    # 车牌检测
    ocr_model_path: "weight/plate_rec_color.pth"    # 车牌ocr
    config: 0.3
    classes: [0,1]
    imgsz: 0  # 0 代表模型不采用原图大小
    # SAHI配置（可选）
    enable_sahi: true  # 是否启用SAHI切片推理
    sahi_config:
      initial_confidence: 0.15  # SAHI初始检测置信度
      device: null  # 自动选择设备，可指定"cuda:0"或"cpu"
      slice_params:  # 可选的自定义切片参数，如为空则自动确定
        # slice_height: 512
        # slice_width: 512
        # overlap_height_ratio: 0.25
        # overlap_width_ratio: 0.25

  5:
    model_name: "car"
    class_path: "model_library.model.car_model.CarModel"
    model_path: "weight/yolo_visdrone.pt"    # 车辆检测
    config: 0.5
    classes: [3,4,5,8]
    imgsz: 0  # 0 代表模型不采用原图大小
  
  6:
    model_name: "infrared"
    class_path: "model_library.model.base_model.BaseModel"
    # model_path: "weight/yolo_infrared.pt"    # 红外行人检测
    model_path: "weight/yolo_infrared_v2.pt"    # 红外行人检测_20251023
    config: 0.3
    classes: [0,1]
    imgsz: 0  # 0 代表模型不采用原图大小

  7:
    model_name: "face_detect"
    class_path: "model_library.model.base_model.BaseModel"
    model_path: "weight/yolov11n-face.pt"    # 人脸检测
    config: 0.3
    conf: 0.3
    classes: [0]
    imgsz: 1  # 1 代表模型采用原图大小


mqtt:
  host: "10.5.52.56"
  port: 1884
  username: "admin"
  password: "zkyy@2024"
  client-id: "model_library"


minio:
  endpoint: "113.105.137.161"
  port: 10019
  access-key: "zkyy"
  secret-key: "Zkyy2021"
  bucket: "cloud-bucket"
